apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: topicapp
  namespace: argocd
spec:
  project: cluster-management
  source:
    repoURL: https://github.com/yannicksiewe/argocd-kafka-lab.git
    targetRevision: HEAD
    path: kafka-cluster/topics
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
